### ISSUE TITLE
Config error in ArchotechBrainMelder: has null thingClass

### ISSUE THREAD

**Issue by KirillRum** [Teok25/Archotech-Expanded#1]
![image](https://user-images.githubusercontent.com/109568200/192510537-d37f74b9-58b9-4c8f-8b9e-300da17d9ed4.png)
Config error in ArchotechBrainMelder: has null thingClass.
UnityEngine.StackTraceUtility:ExtractStackTrace ()
Verse.Log:Error (string)
Verse.DefDatabase`1<Verse.ThingDef>:ErrorCheckAllDefs ()
System.Reflection.MonoMethod:Invoke (object,System.Reflection.BindingFlags,System.Reflection.Binder,object[],System.Globalization.CultureInfo)
System.Reflection.MethodBase:Invoke (object,object[])
Verse.GenGeneric:InvokeStaticMethodOnGenericType (System.Type,System.Type,string)
Verse.PlayDataLoader:DoPlayLoad ()
Verse.PlayDataLoader:LoadAllPlayData (bool)
Verse.Root/<>c:<Start>b__6_1 ()
Verse.LongEventHandler:RunEventFromAnotherThread (System.Action)
Verse.LongEventHandler/<>c:<UpdateCurrentAsynchronousEvent>b__27_0 ()
System.Threading.ThreadHelper:ThreadStart_Context (object)
System.Threading.ExecutionContext:RunInternal (System.Threading.ExecutionContext,System.Threading.ContextCallback,object,bool)
System.Threading.ExecutionContext:Run (System.Threading.ExecutionContext,System.Threading.ContextCallback,object,bool)
System.Threading.ExecutionContext:Run (System.Threading.ExecutionContext,System.Threading.ContextCallback,object)
System.Threading.ThreadHelper:ThreadStart ()

**Comment by KirillRum** [comment]
I cant open debug actions menu, I think it's because of this

**Comment by KirillRum** [comment]
And, 
![image](https://user-images.githubusercontent.com/109568200/192511508-1af507fc-bf6c-4eb2-bb0c-39919ffb372d.png)
XML error: Could not find parent node named "ImplantBase" for node "ThingDef". Full node: <ThingDef ParentName="ImplantBase"><defName>ArchotechBrainMelder</defName><label>archotech brain melder</label><description>An impressive feat of medical engineering using attomachines. These leak from the main hub into the bloodstream which constantly heal any long term scars. However, the main control hub for these attomachines resides in the Parietal lobe and parts of the Cerebellum, removing the subject's sense of pain, while overall increasing conciousness and happiness. Further study of the device finds contradictions in the laws of quantumn physics as well as a high probability of artificial sentience residing within. It's workings are near-impossible for the human mind to concieve.</description><graphicData><texPath>Things/Item/Health/HealthItemBionic</texPath><graphicClass>Graphic_Single</graphicClass><drawSize>0.80</drawSize></graphicData><thingSetMakerTags><li>RewardSpecial</li></thingSetMakerTags><statBases><MarketValue>800</MarketValue><Mass>0.2</Mass><WorkToMake>100</WorkToMake></statBases><recipeMaker><researchPrerequisite>ArchotechMimicry</researchPrerequisite><recipeUsers><li>BasicArchotechWorkbench</li></recipeUsers></recipeMaker><costList><Attomachinery>10</Attomachinery><ComponentSpacer>5</ComponentSpacer></costList><techHediffsTags><li>Archotech</li></techHediffsTags></ThingDef>
UnityEngine.StackTraceUtility:ExtractStackTrace ()
Verse.Log:Error (string)
Verse.XmlInheritance:GetBestParentFor (Verse.XmlInheritance/XmlInheritanceNode,string)
Verse.XmlInheritance:ResolveParentsAndChildNodesLinks ()
Verse.XmlInheritance:Resolve ()
Verse.LoadedModManager:ParseAndProcessXML (System.Xml.XmlDocument,System.Collections.Generic.Dictionary`2<System.Xml.XmlNode, Verse.LoadableXmlAsset>)
Verse.LoadedModManager:LoadAllActiveMods ()
Verse.PlayDataLoader:DoPlayLoad ()
Verse.PlayDataLoader:LoadAllPlayData (bool)
Verse.Root/<>c:<Start>b__6_1 ()
Verse.LongEventHandler:RunEventFromAnotherThread (System.Action)
Verse.LongEventHandler/<>c:<UpdateCurrentAsynchronousEvent>b__27_0 ()
System.Threading.ThreadHelper:ThreadStart_Context (object)
System.Threading.ExecutionContext:RunInternal (System.Threading.ExecutionContext,System.Threading.ContextCallback,object,bool)
System.Threading.ExecutionContext:Run (System.Threading.ExecutionContext,System.Threading.ContextCallback,object,bool)
System.Threading.ExecutionContext:Run (System.Threading.ExecutionContext,System.Threading.ContextCallback,object)
System.Threading.ThreadHelper:ThreadStart ()

**Comment by Teok25** [comment]
This repository is completely outdated even by 1.3 standards.

**Comment by Teok25** [comment]
I'll be doing some work on this soon, but it will most likely be in a new repository on a different GitHub account. I'll let you know when that goes live.

**Comment by Teok25** [comment]
new repository updated for 1.4 here: https://github.com/teok24/Archotech-Expanded

**Comment by KirillRum** [comment]
Thank
